{% set name = "excels2vensim" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/excels2vensim-{{ version }}.tar.gz
  sha256: b6bc368cff9f1b7c1a35f56f0a13416c85664d3bd8d00943ff99663482857103

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - pysd >=3.12
    - python >=3.9

test:
  imports:
    - excels2vensim
    - excels2vensim.cli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SDXorg/excels2vensim
  summary: Easy write excel inputs in Vensim
  license: MIT
  license_file: LICENSE
  doc_url: https://excels2vensim.readthedocs.io/
  dev_url: https://github.com/SDXorg/excels2vensim

extra:
  recipe-maintainers:
    - enekomartinmartinez
